version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
    # TODO: Replace this with dockersecrets or something
      - REPLICATE_API_PROFILE="yorkey"

networks:
  mynetwork:
