# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: ./frontend
    dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
